### ISSUE TITLE
Undefined array key "Sample"

### ISSUE THREAD

**Issue by shijie1991** [guanguans/laravel-soar#27]
Laravel Framework 9.9.0
PHP 8.1.1 

/vendor/guanguans/laravel-soar/src/Bootstrapper.php  160 行 报错 

我在  getScores() 方法 打印 $score 
![image](https://user-images.githubusercontent.com/11606404/165013079-3d243b56-e954-4249-8268-eab8ac2f6562.png)

**Comment by guanguans** [comment]
@shijie1991 看样子好像用的旧版本的 soar，麻烦查看一下 `laravel-soar`、`guanguans/soar-php` 的版本。

```bash
╰─ composer show guanguans/laravel-soar                                                                                                                                ─╯
name     : guanguans/laravel-soar
descrip. : SQL optimizer and rewriter for laravel. - laravel 的 SQL 优化器和重写器。
keywords : debug, laravel, mysql, optimize, optimizer, rewrite, rewriter, soar, sql, statement, 优化器, 重写器
versions : * v2.0.12
type     : laravel
```

```bash
╰─ composer show guanguans/soar-php                                                                                                                                    ─╯
name     : guanguans/soar-php
descrip. : SQL optimizer and rewriter.
keywords : debug, mysql, optimizer, rewriter, soar, sql, sql optimizer, sql rewriter
versions : * v2.5.7
type     : library
```

**Comment by shijie1991** [comment]
composer show guanguans/laravel-soar
name     : guanguans/laravel-soar
descrip. : SQL optimizer and rewriter for laravel. - laravel 的 SQL 优化器和重写器。
keywords : debug, laravel, mysql, optimize, optimizer, rewrite, rewriter, soar, sql, statement, 优化器, 重写器
versions : * v2.0.12


composer show guanguans/soar-php
name     : guanguans/soar-php
descrip. : SQL optimizer and rewriter.
keywords : debug, mysql, optimizer, rewriter, soar, sql, sql optimizer, sql rewriter
versions : * v2.5.7

**Comment by guanguans** [comment]
@shijie1991 你是自己又单独配置了 soar 了吗，官方的没有我这边的新 [`https://github.com/guanguans/soar-php/blob/master/bin/soar.darwin-amd64`](https://github.com/guanguans/soar-php/blob/master/bin/soar.darwin-amd64) 是前阵子刚自己编译的。

**Comment by shijie1991** [comment]
path 引用 guanguans/soar-php/bin/soar.darwin-amd64

 chmod +x soar.darwin-amd64

Guanguans\SoarPHP\Soar::score(): Return value must be of type string, null returned

**Comment by shijie1991** [comment]
'path' => env('SOAR_PATH'), 未配置的情况下 也是 

Guanguans\SoarPHP\Soar::score(): Return value must be of type string, null returned

**Comment by guanguans** [comment]
@shijie1991 可以微信沟通吗？微信号发我邮箱，ityaozm@gmail.com

**Comment by shijie1991** [comment]
已发送

**Comment by shijie1991** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/11606404/165019419-93a608aa-9d53-4a13-9dd2-aef073859010.png">

**Comment by guanguans** [comment]
@shijie1991 你转发一下我的这个邮箱吧 53222411@qq.com，谷歌那个到现在还没收到。

**Comment by guanguans** [comment]
> <img alt="image" width="663" src="https://user-images.githubusercontent.com/11606404/165019419-93a608aa-9d53-4a13-9dd2-aef073859010.png">

可以了吗，到目前我还没收到邮件，方便的话微信号发我这个邮箱吧 [53222411@qq.com](mailto:53222411@qq.com)，微信沟通方便一些。

**Comment by shijie1991** [comment]
@guanguans 下午有点事儿 已发送
