### ISSUE TITLE
laravel-soar/src/Support/Macros/QueryBuilderMacro.php 文件toRawSql方法在php8.1下会报参数类型错误，建议修改如下

### ISSUE THREAD

**Issue by twitf** [guanguans/laravel-soar#31]
```
        return array_reduce($bindings, function ($sql, $binding) {
            return preg_replace('/\?/', is_numeric($binding) ? (string)$binding : "'" . $binding . "'", $sql, 1);
        },                  $querySql);
```
> 增加强制转换为字符串类型解决此报错`(string)$binding`，也兼容低版本

**Comment by twitf** [comment]
我的和你不太一样 不过关键点就是这个类型问题

**Comment by guanguans** [comment]
> ```
>         return array_reduce($bindings, function ($sql, $binding) {
>             return preg_replace('/\?/', is_numeric($binding) ? (string)$binding : "'" . $binding . "'", $sql, 1);
>         },                  $querySql);
> ```
> 
> > 增加强制转换为字符串类型解决此报错`(string)$binding`，也兼容低版本

感谢反馈，我稍后修复一下。

**Comment by guanguans** [comment]
@twitf 以修复，请尝试更新到最新版本。

**Comment by twitf** [comment]
很棒，这对我影响不大。我借鉴了你的这部分代码

**Comment by guanguans** [comment]
> 很棒，这对我影响不大。我借鉴了你的这部分代码

感兴趣的话，我另外一个项目有一些有用的 Macros([https://github.com/guanguans/laravel-skeleton/tree/master/app/Macros](https://github.com/guanguans/laravel-skeleton/tree/master/app/Macros))
