### ISSUE TITLE
M1 Homestead 安装提示错误， 似乎 M1 安装不了

### ISSUE THREAD

**Issue by gyp719** [guanguans/laravel-soar#39]
![image](https://github.com/guanguans/laravel-soar/assets/30563368/b3e0f81d-2b3a-45c7-ac2e-fe35681884cd)

**Comment by guanguans** [comment]
@gyp719 .env 文件中尝试配置 sudo 密码再试一下。

```shell
SOAR_SUDO_PASSWORD='your sudo password' # 设置 sudo 密码，以 sudo 运行 soar 命令，避免出现上述错误。
```

如还有报错的话，复制报错命令到终端执行，查看是否能够正常执行。

**Comment by gyp719** [comment]
> ```shell
> SOAR_SUDO_PASSWORD='your sudo password'
> ```

<img width="1352" alt="image" src="https://github.com/guanguans/laravel-soar/assets/30563368/e06766fc-2f77-4f74-8ed6-6ac4ea515e21">

依旧还是不行， 是我运行的命令不正确吗？

**Comment by guanguans** [comment]
@gyp719 目前没有打 linux arm 架构的包。如果现在想在你 m1 的 homestead 中运行的话得自己去 soar 的源码打一个二进制文件，自己配置一下路径即可。我这边有时间了也加一下。或者你可以在宿主机上先直接安装试试，然后宿主机上 `artisan serve` 启动服务试试。

**Comment by gyp719** [comment]
> @gyp719 目前没有打 linux arm 架构的包。如果现在想在你 m1 的 homestead 中运行的话得自己去 soar 的源码打一个二进制文件，自己配置一下路径即可。我这边有时间了也加一下。或者你可以在宿主机上先直接安装试试，然后宿主机上 `artisan serve` 启动服务试试。

去 soar 的源码打一个二进制文件 这可就难住我了， 等老大优化吧

**Comment by guanguans** [comment]
@gyp719 新版本已包含 Linux arm 架构包，尝试更新到最新版本。

```shell
composer require guanguans/laravel-soar:^3.8 --dev -v
```

**Comment by gyp719** [comment]
感谢大佬， 刚刚测试了，可以使用。

但是有2个问题咨询下：
1、Console 有提示找不到文件
2、看上面有一个示例图， 显示在 Dcat Admin 后台页面， 如何进行操作？

**Comment by guanguans** [comment]
> 感谢大佬， 刚刚测试了，可以使用。
> 
> 但是有2个问题咨询下：
> 1、Console 有提示找不到文件
> 2、看上面有一个示例图， 显示在 Dcat Admin 后台页面， 如何进行操作？

1 、我没太懂什么意思，有报错可以贴出来异常上下文我来看看。
2、这个包会自动监控生命周期中的数据库操作。测试的话你只需要写几条查询语句就可以展示了。如果是一个web请求，会自动在页面下面显示一个 soar bar。如果是一个json请求会，附加在 json 响应中。如果是一个命令，会记录在 soar 日志中。

**Comment by gyp719** [comment]
<img width="1358" alt="image" src="https://github.com/guanguans/laravel-soar/assets/30563368/2f519596-3e3d-4281-b72f-a1f45719e81a">

**Comment by guanguans** [comment]
> <img width="1358" alt="image" src="https://github.com/guanguans/laravel-soar/assets/30563368/2f519596-3e3d-4281-b72f-a1f45719e81a">
> 

后面的看不到了，你直接把这个报错的整个日志文字贴过来。

**Comment by gyp719** [comment]
[2023-07-23 22:18:50] local.ERROR: file_get_contents(/home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/../../../vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/font-awesome/fonts/fontawesome-webfont.ttf): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_get_contents(/home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/../../../vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/font-awesome/fonts/fontawesome-webfont.ttf): Failed to open stream: No such file or directory at /home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/AssetController.php:64)
[stacktrace]
#0 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/AssetController.php(64): file_get_contents()
#3 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Guanguans\\LaravelSoar\\Http\\Controllers\\AssetController->font()
#4 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#6 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#7 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
#10 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#11 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#12 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#13 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#14 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#15 /home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Middleware/OutputSoarScoresMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Guanguans\\LaravelSoar\\Http\\Middleware\\OutputSoarScoresMiddleware->handle()
#17 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#19 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#20 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#23 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#25 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#27 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#29 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#31 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#33 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#34 /home/vagrant/Code/Tools/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#35 {main}
"}

**Comment by guanguans** [comment]
> [2023-07-23 22:18:50] local.ERROR: file_get_contents(/home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/../../../vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/font-awesome/fonts/fontawesome-webfont.ttf): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_get_contents(/home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/../../../vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/font-awesome/fonts/fontawesome-webfont.ttf): Failed to open stream: No such file or directory at /home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/AssetController.php:64)
> [stacktrace]
> #0 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
> #1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
> #2 /home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Controllers/AssetController.php(64): file_get_contents()
> #3 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Guanguans\\LaravelSoar\\Http\\Controllers\\AssetController->font()
> #4 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
> #5 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
> #6 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
> #7 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
> #8 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #9 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
> #10 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
> #11 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
> #12 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
> #13 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
> #14 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
> #15 /home/vagrant/Code/Tools/vendor/guanguans/laravel-soar/src/Http/Middleware/OutputSoarScoresMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #16 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Guanguans\\LaravelSoar\\Http\\Middleware\\OutputSoarScoresMiddleware->handle()
> #17 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #18 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
> #19 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
> #20 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #21 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
> #22 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
> #23 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #24 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
> #25 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #26 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
> #27 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #28 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
> #29 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #30 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
> #31 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> #32 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
> #33 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
> #34 /home/vagrant/Code/Tools/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
> #35 {main}
> "} 
> 

这个我明天看一下。目前 json 输出和 soar 日志中的评分输出是正常的吧。

**Comment by gyp719** [comment]
目前 json 输出和 soar 日志中的评分输出是正常， 在日志是的下面就会有报错的信息输出。

**Comment by guanguans** [comment]
@gyp719 更新到最新版本你再试试。

**Comment by gyp719** [comment]
好的，马上试试。

**Comment by gyp719** [comment]
> @gyp719 更新到最新版本你再试试。
感谢大佬， ok了， 可以了

**Comment by guanguans** [comment]
> 感谢大佬， 刚刚测试了，可以使用。
> 
> <img alt="image" width="704" src="https://user-images.githubusercontent.com/30563368/255397164-29c95642-e624-4db4-8de7-ff7933c8f8fb.png">
> 但是有2个问题咨询下： 1、Console 有提示找不到文件 2、看上面有一个示例图， 显示在 Dcat Admin 后台页面， 如何进行操作？ 3、生产的sql 分析预计， 如何显示在 soar.log 日志中？

刚看到第三条。将生产环境的数据库配置配在 `-online-dsn` 选项上，将 `-online-dsn` 的 `disable` 配置为 `false`。然后本地运行即可。

```php
<?php

return [
    // 是否启用 soar 评分
    'enabled' => (bool) env('SOAR_SCORE_ENABLED', config('app.debug')),

    // +----------------------------------------------------------------------+//
    // |              请参考 @see https://github.com/XiaoMi/soar               |//
    // +----------------------------------------------------------------------+//
    'options' => [
        // TestDSN, 测试环境数据库配置, username:********@tcp(ip:port)/schema (default "tcp/information_schema?timeout=3s&charset=utf8").
        '-test-dsn' => [
            'host' => env('SOAR_TEST_DB_HOST', config('database.connections.mysql.host', 'you_host')),
            'port' => env('SOAR_TEST_DB_PORT', config('database.connections.mysql.port', 'you_port')),
            'dbname' => env('SOAR_TEST_DB_DATABASE', config('database.connections.mysql.database', 'you_dbname')),
            'username' => env('SOAR_TEST_DB_USERNAME', config('database.connections.mysql.username', 'you_username')),
            'password' => env('SOAR_TEST_DB_PASSWORD', config('database.connections.mysql.password', 'you_password')),
            'disable' => env('SOAR_TEST_DB_DISABLE', false),
        ],

        // OnlineDSN, 线上环境数据库配置(数据库用户只需 select 权限), username:********@tcp(ip:port)/schema (default "tcp/information_schema?timeout=3s&charset=utf8").
        '-online-dsn' => [
            'host' => env('SOAR_ONLINE_DB_HOST', config('database.connections.mysql.host', 'you_host')),
            'port' => env('SOAR_ONLINE_DB_PORT', config('database.connections.mysql.port', 'you_port')),
            'dbname' => env('SOAR_ONLINE_DB_DATABASE', config('database.connections.mysql.database', 'you_dbname')),
            'username' => env('SOAR_ONLINE_DB_USERNAME', config('database.connections.mysql.username', 'you_username')),
            'password' => env('SOAR_ONLINE_DB_PASSWORD', config('database.connections.mysql.password', 'you_password')),
            'disable' => env('SOAR_ONLINE_DB_DISABLE', true),
        ],
    ],
];
```

**Comment by gyp719** [comment]
感谢大佬的指导， 看到大佬在 [Packagist](https://packagist.org/?query=guanguans) 发布了好多包

**Comment by guanguans** [comment]
> 感谢大佬的指导， 看到大佬在 [Packagist](https://packagist.org/?query=guanguans) 发布了好多包

😃 可以尝试用用其他包，点个star支持一下。

**Comment by gyp719** [comment]
> > 感谢大佬的指导， 看到大佬在 [Packagist](https://packagist.org/?query=guanguans) 发布了好多包
> 
> 😃 可以尝试用用其他包，点个star支持一下。

好的， 没问题。
