### ISSUE TITLE
输出响应中间件格式问题

### ISSUE THREAD

**Issue by kbdxbt** [guanguans/laravel-soar#55]
https://github.com/guanguans/laravel-soar/blob/d99ae267e97c6ac26910a465979cd7b24816d237/src/Http/Middleware/OutputSoarScoresMiddleware.php#L34

如果接口输出的是文件流格式，这里会出现错误，自己试了下这样改是可以

`
       
        $response = $next($request);

        if (
            $response instanceof JsonResponse &&
            is_object($response->getData())
        ) {
            return tap($next($request), fn(Response $response) => $this->outputManager->output(
                $this->bootstrapper->getScores(),
                $response
            ));
        }

        return $next($request);

`

**Comment by guanguans** [comment]
具体是哪个输出器，输出的不对，应该在输出器的条件里面改的

**Comment by kbdxbt** [comment]
> 具体是哪个输出器，输出的不对，应该在输出器的条件里面改的

src/Outputs/SoarBarOutput.php  这个输出器如果是文件流格式输出的话就会报错，你看下是不是也存在这样的问题

**Comment by guanguans** [comment]
> > 具体是哪个输出器，输出的不对，应该在输出器的条件里面改的
> 
> src/Outputs/SoarBarOutput.php  这个输出器如果是文件流格式输出的话就会报错，你看下是不是也存在这样的问题

嗯，我有时间看看，你暂时可以先在配置中除掉。

**Comment by guanguans** [comment]
@kbdxbt 可以提供一下你的代码吗，我这边没有复现出来。

**Comment by kbdxbt** [comment]
@guanguans

**Comment by guanguans** [comment]
@kbdxbt 更新到最新版本试试。

**Comment by kbdxbt** [comment]
@guanguans 试了下可以了
